[package]
name = "list2"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-bigint = { version = "0.6", features = ["zeroize"] }
hex = "0.4"
base64 = "0.21"
rand = "0.8"
num-traits = "0.2.19"
subtle = "2.5"
