[package]
name = "list3"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = { version = "0.6", features = ["zeroize"] }
hex = "0.4"
subtle = "2.5"
list2 = { path = "../list2" }
sha2 = "0.10.9"
serde_json = "1.0.149"
